### ISSUE TITLE
Group messages

### ISSUE THREAD

**Issue by ivkram** [EvanEnev/Astronomy-Picture-of-the-Day-Bot#1]
Попробовал добавить бота в группу, но увидел следующее:

> has no access to messages

Было бы здорово поменять `Group Privacy` в настройках бота, чтобы он мог отправлять сообщения в группах:

`@BotFather bot >> Bot Settings >> Group Privacy >> Turn off`

**Comment by EvanEnev** [comment]
На отправку сообщений это не влияет. Эта настойка запрещает боту получать сообщения, но он продолжает получать команды через '/'.
После добавления бота в группу используйте команду /subscribe

**Comment by ivkram** [comment]
Спасибо за ответ!
